name: Deploy standalone plugins to WordPress.org

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      slug:
        type: string
        description: 'The slug of the plugin to deploy'
      version:
        type: string
        description: 'The version of the plugin to deploy'

jobs:
  release:
    name: New Release
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set matrix
        id: set-matrix
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }}; then
            # Set the manual input values in JSON format for use in the matrix.
            echo "matrix={\"include\":[{\"slug\":\"${{ inputs.slug }}\",\"version\":\"${{ inputs.version }}\"}]}" >> $GITHUB_OUTPUT
          else
            # Load the JSON file and parse from "{name: {slug, version}, ...}" to "include: [{ name, slug, version }, ...]"
            # for use in the matrix.
            echo "matrix="$(jq -c '{include:[keys[] as $k | {name:$k,slug:.[$k].slug,version:.[$k].version }]}' plugins.json) >> $GITHUB_OUTPUT
          fi
  deploy:
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.release.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Building standalone plugins
        run: npm run build-plugins
      - name: Deploy Standalone Plugin - ${{ matrix.slug }}
        # TODO Once the workflow is tested, we will remove the comment and use the 10up action to deploy the plugin.
        #uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          # TODO Once the workflow is tested, we will remove the comment and use the secret SVN access.
          #SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          #SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          # TODO Once the workflow is tested, we will remove this test credential.
          SVN_PASSWORD: SVN_PASSWORD
          SVN_USERNAME: SVN_USERNAME
          SLUG: ${{ matrix.slug }}
          VERSION: ${{ matrix.version }}
          BUILD_DIR: ./build/${{ matrix.slug }}
          ASSETS_DIR: ./build/${{ matrix.slug }}/.wordpress-org
        # TODO The script will be removed once the workflow is tested.
        run: bash ./deploy.sh
